# Generated by Django 5.2.6 on 2025-09-06 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('conversation_context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfluencePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('space_key', models.CharField(max_length=50)),
                ('page_type', models.CharField(default='page', max_length=50)),
                ('last_updated', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JiraProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_key', models.CharField(max_length=20, unique=True)),
                ('project_name', models.CharField(max_length=200)),
                ('project_id', models.CharField(max_length=50)),
                ('lead_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JiraUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_account_id', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.CharField(max_length=50)),
                ('keywords', models.JSONField(default=list)),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('intent_detected', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response_type', models.CharField(default='text', max_length=50)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_chat.chatsession')),
            ],
        ),
        migrations.AddField(
            model_name='chatsession',
            name='current_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_chat.jiraproject'),
        ),
        migrations.CreateModel(
            name='JiraTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_key', models.CharField(max_length=50, unique=True)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('issue_type', models.CharField(choices=[('Task', 'Task'), ('Bug', 'Bug'), ('Story', 'Story'), ('Epic', 'Epic'), ('Subtask', 'Subtask')], default='Task', max_length=50)),
                ('priority', models.CharField(choices=[('Lowest', 'Lowest'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Highest', 'Highest')], default='Medium', max_length=50)),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Code Review', 'Code Review'), ('Testing', 'Testing'), ('Done', 'Done')], default='To Do', max_length=50)),
                ('created_by_chat', models.BooleanField(default=False)),
                ('jira_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_chat.chatsession')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_chat.jiraproject')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='ai_chat.jirauser')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tickets', to='ai_chat.jirauser')),
            ],
        ),
        migrations.CreateModel(
            name='TicketCreationFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(choices=[('started', 'Started'), ('got_summary', 'Got Summary'), ('got_description', 'Got Description'), ('got_project', 'Got Project'), ('got_assignee', 'Got Assignee'), ('got_priority', 'Got Priority'), ('completed', 'Completed')], default='started', max_length=50)),
                ('collected_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_chat.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='TicketSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_text', models.TextField()),
                ('steps_taken', models.JSONField(default=list)),
                ('time_to_resolve', models.DurationField(blank=True, null=True)),
                ('success_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('tags', models.JSONField(default=list)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ai_chat.jiraticket')),
            ],
        ),
    ]
