# Generated by Django 5.2.6 on 2025-09-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiraAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjiraprofile',
            name='jira_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
